#!/usr/bin/env sh

yabai -m config debug_output on # Debug mode

# global settings
# focus window that your mouse hovers on (disabled due to right click bugs)
yabai -m config focus_follows_mouse          off
# move mouse to focused window
yabai -m config mouse_follows_focus          off
yabai -m config window_placement             second_child
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
# don't automatically rebalance windows
yabai -m config auto_balance                 off
# swap windows if moved with mouse
yabai -m config mouse_action1                move
# resize windows if resized with mouse
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# SIP Required
# prevent border from being under the active window
yabai -m config window_shadow                off
yabai -m config window_opacity               off

# ignored apps
# yabai -m rule --add app="^Microsoft Teams$" manage=off
# yabai -m rule --add app="^Blitz$" manage=off
# yabai -m rule --add app="^League of Legends$" manage=off

