command_timeout = 1000

[cmd_duration]
min_time = 500  # only show if slow

[status]
disabled = true

# Git can be expensive; these are common savings:
[git_status]
disabled = true
[git_metrics]
disabled = true
[git_commit]
disabled = true
[package]
disabled = true
[nodejs]
disabled = true
[rust]
disabled = true
[python]
disabled = true
[dotnet]
disabled = true
[battery]
disabled = true
